name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: poedle/buildozer-action@v1.1
        with:
          buildozer_version: stable
