name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git libncurses5:i386 libstdc++6:i386 libgtk2.0-0:i386 libpangox-1.0-0 libpangoxft-1.0-0 libidn11 libglu1-mesa:i386 libasound2:i386 libffi-dev libssl-dev libsqlite3-dev
          sudo apt-get install -y --no-install-recommends openjdk-17-jdk unzip autoconf libtool pkg-config zlib1g-dev libncursesw5-dev libncurses5-dev
          pip install --upgrade pip setuptools wheel Cython buildozer

      - name: Build APK
        run: |
          # إعداد التراخيص يدوياً وتجهيز بيئة Buildozer
          mkdir -p ~/.android
          echo 'count=0' > ~/.android/repositories.cfg
          buildozer android debug
